name: Build and Release the "gatsby-source-surveyjs" Package

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  increase-version:
    name: Increase Semantic Versioning of Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup the Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Increase Package Version
        uses: "phips28/gh-action-bump-version@master"
        id: version-increase
        with:
          tag-prefix: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output the New Package Version
        env:
          NEW_TAG: ${{ steps.version-increase.outputs.newTag }}
        run: echo "New Package Version: $NEW_TAG"
        
  # build:
  #   name: Build Project
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Cache Dependencies
  #       uses: actions/cache@v2
  #       with:
  #         path: |
  #           **/node_modules
  #         key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

  #     - name: Install Dependencies
  #       run: npm install

  #     - name: Build
  #       run: npm run prepare

  # publish-npm:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 12
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 12
  #         registry-url: https://npm.pkg.github.com/
  #     - run: npm ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
